<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-J9THCFRO" ignored="3" name="Default test(failed)" tests="1" failures="1" timestamp="2021-12-22T10:09:14 IST" time="0.25" errors="0">
  <testcase name="secondTestCase" time="0.211" classname="TestNG.sampleTestNG">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNG.sampleTestNG.secondTestCase() didn&amp;apos;t finish within the time-out 200">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNG.sampleTestNG.secondTestCase() didn't finish within the time-out 200
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- secondTestCase -->
  <testcase name="fourthTestCase" time="0.0" classname="TestNG.sampleTestNG">
    <ignored/>
  </testcase> <!-- fourthTestCase -->
  <testcase name="firstTestCase" time="0.0" classname="TestNG.sampleTestNG">
    <ignored/>
  </testcase> <!-- firstTestCase -->
  <testcase name="thirdTestCase" time="0.0" classname="TestNG.sampleTestNG">
    <ignored/>
  </testcase> <!-- thirdTestCase -->
</testsuite> <!-- Default test(failed) -->
